### Recuperar todos los libros
GET http://localhost:4001/books

### Crear un nuevo libro
POST http://localhost:4001/books
Content-Type: application/json

{
    "title": "El club de las 5am",
    "author": "Robin Sharma",
    "year": 2005,
    "genre": "Ficción",
    "image":"https://mentee.es/wp-content/uploads/2021/08/el-club-de-las-5-de-la-manana.png"
}
### Actualizar  información de un libro
PATCH  http://localhost:4001/books/f47ac10b-58cc-4372-a567-0e02b2c3d479
Content-Type: application/json

{
    "title": "El silencio",
    "year": 2017
}
### Eliminar un libro
DELETE http://localhost:4001/books/d3e4f5g6-b7a8-c9d0-e1f2-a3b4c5d6e7f



### Filtrar por genero

###Familiar
GET http://localhost:4001/books/?genre=Familiar

###Thriller
GET http://localhost:4001/books?genre=Thriller

###Ficción
GET http://localhost:4001/books?genre=Ficción


### Rango de año 
GET http://localhost:4001/books?year=1990-2010